name: Fly Deploy
on: 
  workflow_dispatch: # 手动触发
  #schedule:
    #- cron: '0 4 1 * *'
  #push:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}
  #UUID: ${{ secrets.UUID }}--不用~
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
             retain_days: 2
             keep_minimum_runs: 6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          sh ./deploy.sh
